package demo;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import demo.DemoApplication;
import org.junit.Test;
import static org.junit.Assert.*;

public class DemoApplicationTest {
    @Test public void testSomeLibraryMethod() {
        DemoApplication classUnderTest = new DemoApplication();
        assertTrue("someLibraryMethod should return 'true'", true);
    }
    @Test public void testNoMorefail() {
        assertTrue(true);
    }
}
